pipeline{
    agent any
    tools {maven 'Maven-3.5.2'}
    triggers {         
        pollSCM('H/3 * * * *')     
    }
    
    stages {
        stage('Checkout'){
            steps{
                git branch: 'dev', url :'https://github.com/LucMartin91/Devops'
            }
        }
        
       stage('Compilation') {
            steps {
                script {
                    // Compile le projet sans exécuter les tests
                    sh 'mvn -f demo/demo/pom.xml clean compile -DskipTests'
                }
            }
        }
        
        stage('Javadoc'){
            steps{
                script {
                sh 'mvn -f demo/demo/pom.xml javadoc:javadoc'
                }
            }
        }
        
    }
}
